### ISSUE TITLE
API model for persons lacks granular privacy

### ISSUE THREAD

**Issue by Jason-Gush** [new-zealand-research-information-system/nzris-api-specifications#1]
'persons' as a entity have a single protectionRequirements block, i.e.,
everything about a person shares the same protection.
In most instances this will make everything about a person protected.
What is needed is the ability to specify protection for each of:
        "dateOfBirth"
        "gender"
        "genderOtherInformation"
        "ethnicity" - each item
        "iwiAffiliation" - each item
        "sectorPersonIds" - each item
        "researchCareerStage" - each item
        "academicRecord" - each item
        "recognition" - each item
        "professionalBodies" - each item
        "organisationAffiliations" - each item
With the current model, to publish someone's name appears to also require
publishing their DOB, gender, and ethnicity.

**Comment by chrisdangerfield** [comment]
Kia ora Jason,

Thanks for raising this one. Looks like this might be an issue with how we have structured our "Protection Patterns" in the [data specifications](https://www.mbie.govt.nz/assets/3c7d27b71b/NZRIS-Data-Specification-2.0.pdf). We had constructed these to be as simple as possible, while being able to appropriately protect data. It sounds like you need more granular control. This is a good thing to consider for the next data specifications update, happy to discuss further if it causes issues with providing the initial tranche of data.

Ngā mihi nui,
Chris

**Comment by Jason-Gush** [comment]
Yes a pithy one here.  

In the first tranche, this will mean that everything to do with a person is likely going to be protected under '05' Personal Identifiable.  That seems conservative, but is perhaps the better for that.  We can cope with the fact that while our team members names (and affiliations) are public, they won't be visible in the early NZRIS releases.

**Comment by chrisdangerfield** [comment]
Right. Yes. Does sound tricky. Would it work in the first instance to submit mandatory fields and leave out optional fields that you think might need to be protected?

**Comment by chrisdangerfield** [comment]
Kia ora @Jason-Gush,

I am keen to transfer this issue to the data specifications repository - as any changes will then flow into the API - but will be made there first. Is this ok with you?

Ngā,
Chris

**Comment by Jason-Gush** [comment]
Kia ora @chrisdangerfield.
Of course :).
