### ISSUE TITLE
academicRecord too promiscuous in academicQualification and discipline

### ISSUE THREAD

**Issue by Jason-Gush** [new-zealand-research-information-system/nzris-api-specifications#2]
https://github.com/new-zealand-research-information-system/nzris-api-specifications/blob/b8264a3d66d209730a66b5183a5bcb8244dc2328/submission-example.json#L662

person > academicRecord doesn't bear a lot of similarity to "12.c Academic Record (obl = 0..*)" in the NZRIS-input-template-2.0.xlsx

The model is ambiguous about whether NZREG (and NZSCEDFIELD) or ISCED-P (and ISCED-F) should be used, seemingly taking in both.  NB the template xlsx has both as oblig for an academic record entry.

**Comment by chrisdangerfield** [comment]
Kia ora Jason,

Thanks for raising this. Looks like we are doubled up on the qualifications in the [input spreadsheet](https://www.mbie.govt.nz/assets/a20fb48a11/NZRIS-input-template-2.0.xlsx). You should be able to provide either the international standards (ISCED-P for the qualification, and ISCED-F for the discipline) or the New Zealand standards (NZREG for the qualification, and NZSCEDFIELD for the discipline). And good spotting on the obligations. We will look into this.

Ngā,
Chris

**Comment by Jason-Gush** [comment]
Mōrena Chris, 
Great to see all this action.  With regard to promiscuity, perhaps a qualification standard type
 flag would be helpful, i.e., similar to how the other multi-source identifiers are handled cf.
personIDType and organisationIDType

**Comment by chrisdangerfield** [comment]
Kia ora Jason,

Thanks for your discussion on this. Yes, a flag sounds like a good thing to consider for a future data specification revision.

Looking into the spreadsheet a bit further we have split out the international standards (ISCED) and the national standards (NZREG and NZSCED-FIELD), but the names of the fields and the obligations (mandatory for qualification, and optional for discipline) look like they are aligning with the specifications. But, yes, either codeset could be used for this one field in the API specifications.

Does that answer your question?

Ngā,
Chris

**Comment by chrisdangerfield** [comment]
I have created an [issue in the data specifications repository](https://github.com/new-zealand-research-information-system/nzris-data-specifications/issues/13) to consider a flag.
